CREATE TABLE answers (
    id int  NOT NULL,
    question_id int  NOT NULL,
    answer varchar(100)  NOT NULL,
    is_correct boolean  NOT NULL,
    points real  NOT NULL,
    CONSTRAINT answers_pk PRIMARY KEY (id)
);

CREATE TABLE questions (
    id int  NOT NULL,
    question varchar(300)  NOT NULL,
    image_link bytea NULL,
    type varchar NOT NULL,
    CONSTRAINT questions_pk PRIMARY KEY (id)
);

CREATE TABLE sets (
    id int NOT NULL,
    test_id int  NOT NULL,
    question_id int  NOT NULL,
    question_position int  NOT NULL,
    CONSTRAINT sets_pk PRIMARY KEY (id)
);

CREATE TABLE users
(
    id int  NOT NULL,
    email varchar(50) UNIQUE NOT NULL,
    index char(6),
    name varchar(20)  NOT NULL,
    surname varchar(30)  NOT NULL,
    nickname varchar(20)  NOT NULL,
    password varchar(100)  NOT NULL,
    role_id int NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);


CREATE TABLE roles (
    id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Description varchar(50)  NOT NULL,
    CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE tests (
    id int  NOT NULL,
    name varchar(70)  NOT NULL,
    description varchar(1000)  NULL,
    created_date timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tests_pk PRIMARY KEY (id)
);

CREATE TABLE test_history (
    id int  NOT NULL,
    test_name varchar(50)  NOT NULL,
    content text NOT NULL,
    created_date timestamp  NOT NULL,
    CONSTRAINT test_history_pk PRIMARY KEY (id)
);

CREATE TABLE user_results (
    id int  NOT NULL,
    user_id int  NOT NULL,
    test_history_id int  NOT NULL,
    answers varchar(10000)  NOT NULL,
    score DECIMAL(10, 2)  NOT NULL,
    CONSTRAINT user_results_pk  PRIMARY KEY (id)
);

CREATE TABLE user_personality_results (
    id int  NOT NULL,
    user_result_id int  NOT NULL,
    socializer DECIMAL(10,2)  NOT NULL,
    killer DECIMAL(10, 2)  NOT NULL,
    achiever DECIMAL(10, 2)  NOT NULL,
    explorer DECIMAL(10, 2)  NOT NULL,
    CONSTRAINT user_personality_results_pk  PRIMARY KEY (id)
);

CREATE TABLE games (
    id int  NOT NULL,
    name varchar(50)  NOT NULL,
    description varchar(300)  NOT NULL,
    CONSTRAINT games_pk PRIMARY KEY (id)
);

CREATE TABLE levels (
    id int  NOT NULL,
    game_id int  NOT NULL,
    name varchar(50) NOT NULL,
    difficulty varchar(20) NOT NULL,
    time int NOT NULL,
    map json  NOT NULL,
    CONSTRAINT levels_pk PRIMARY KEY (id)
);

ALTER TABLE levels ADD CONSTRAINT levels_games
    FOREIGN KEY (game_id)
    REFERENCES games (id)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

ALTER TABLE answers ADD CONSTRAINT answers_questions
    FOREIGN KEY (question_id)
    REFERENCES questions (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE sets ADD CONSTRAINT sets_questions
    FOREIGN KEY (question_id)
    REFERENCES questions (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE sets ADD CONSTRAINT sets_tests
    FOREIGN KEY (test_id)
    REFERENCES tests (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE users ADD CONSTRAINT users_roles
    FOREIGN KEY (role_id)
    REFERENCES roles (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE user_results ADD CONSTRAINT user_result_users
    FOREIGN KEY (test_history_id)
    REFERENCES test_history (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE user_personality_results ADD CONSTRAINT user_personality_results_user_results
    FOREIGN KEY (user_result_id)
    REFERENCES user_results (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

CREATE SEQUENCE tests_id_seq;
ALTER TABLE tests ALTER COLUMN id SET DEFAULT nextval('tests_id_seq');

CREATE SEQUENCE questions_id_seq;
ALTER TABLE questions ALTER COLUMN id SET DEFAULT nextval('questions_id_seq');

CREATE SEQUENCE sets_id_seq;
ALTER TABLE sets ALTER COLUMN id SET DEFAULT nextval('sets_id_seq');

CREATE SEQUENCE answers_id_seq;
ALTER TABLE answers ALTER COLUMN id SET DEFAULT nextval('answers_id_seq');

CREATE SEQUENCE users_id_seq;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

CREATE SEQUENCE test_history_id_seq;
ALTER TABLE test_history ALTER COLUMN id SET DEFAULT nextval('test_history_id_seq');

CREATE SEQUENCE user_results_id_seq;
ALTER TABLE user_results ALTER COLUMN id SET DEFAULT nextval('user_results_id_seq');

CREATE SEQUENCE user_personality_results_id_seq;
ALTER TABLE user_personality_results ALTER COLUMN id SET DEFAULT nextval('user_personality_results_id_seq');

CREATE SEQUENCE games_id_seq;
ALTER TABLE games ALTER COLUMN id SET DEFAULT nextval('games_id_seq');

CREATE SEQUENCE levels_id_seq;
ALTER TABLE levels ALTER COLUMN id SET DEFAULT nextval('levels_id_seq');

ALTER TABLE questions
ALTER COLUMN id SET DATA TYPE INTEGER,
ALTER COLUMN id SET DEFAULT nextval('questions_id_seq');