CREATE TABLE answers (
    answer_id int  NOT NULL,
    question_id int  NOT NULL,
    answer varchar(100)  NOT NULL,
    is_correct boolean  NOT NULL,
    points real  NOT NULL,
    CONSTRAINT answers_pk PRIMARY KEY (answer_id)
);

CREATE TABLE questions (
    question_id int  NOT NULL,
    question varchar(300)  NOT NULL,
    image_link bytea NULL,
    type varchar NOT NULL,
    CONSTRAINT questions_pk PRIMARY KEY (question_id)
);

CREATE TABLE sets (
    set_id int  NOT NULL,
    test_id int  NOT NULL,
    question_id int  NOT NULL,
    question_position int  NOT NULL,
    CONSTRAINT sets_pk PRIMARY KEY (set_id)
);

CREATE TABLE users
(
    user_id int  NOT NULL,
    email varchar(50) UNIQUE NOT NULL,
    index char(6),
    name varchar(20)  NOT NULL,
    surname varchar(30)  NOT NULL,
    nickname varchar(20)  NOT NULL,
    password varchar(100)  NOT NULL,
    role_id int NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);


CREATE TABLE roles (
    role_id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Description varchar(50)  NOT NULL,
    CONSTRAINT roles_pk PRIMARY KEY (role_id)
);

CREATE TABLE tests (
    test_id int  NOT NULL,
    name varchar(70)  NOT NULL,
    description varchar(1000)  NULL,
    created_date timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tests_pk PRIMARY KEY (test_id)
);

CREATE TABLE test_history (
    id int  NOT NULL,
    test_name varchar(50)  NOT NULL,
    content text NOT NULL,
    created_at timestamp  NOT NULL,
    CONSTRAINT test_history_pk PRIMARY KEY (id)
);

CREATE TABLE user_results (
    id int  NOT NULL,
    user_id int  NOT NULL,
    test_history_id int  NOT NULL,
    answers varchar(10000)  NOT NULL,
    score DECIMAL(10, 2)  NOT NULL,
    CONSTRAINT user_results_pk  PRIMARY KEY (id)
);

ALTER TABLE answers ADD CONSTRAINT answers_questions
    FOREIGN KEY (question_id)
    REFERENCES questions (question_id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE sets ADD CONSTRAINT sets_questions
    FOREIGN KEY (question_id)
    REFERENCES questions (question_id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE sets ADD CONSTRAINT sets_tests
    FOREIGN KEY (test_id)
    REFERENCES tests (test_id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE users ADD CONSTRAINT users_roles
    FOREIGN KEY (role_id)
    REFERENCES roles (role_id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE user_results ADD CONSTRAINT user_results_users
    FOREIGN KEY (test_history_id)
    REFERENCES test_history (id)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

CREATE SEQUENCE tests_id_seq;
ALTER TABLE tests ALTER COLUMN test_id SET DEFAULT nextval('tests_id_seq');

CREATE SEQUENCE questions_id_seq;
ALTER TABLE questions ALTER COLUMN question_id SET DEFAULT nextval('questions_id_seq');

CREATE SEQUENCE sets_id_seq;
ALTER TABLE sets ALTER COLUMN set_id SET DEFAULT nextval('sets_id_seq');

CREATE SEQUENCE answers_id_seq;
ALTER TABLE answers ALTER COLUMN answer_id SET DEFAULT nextval('answers_id_seq');

CREATE SEQUENCE users_id_seq;
ALTER TABLE users ALTER COLUMN user_id SET DEFAULT nextval('users_id_seq');

CREATE SEQUENCE test_history_id_seq;
ALTER TABLE test_history ALTER COLUMN id SET DEFAULT nextval('test_history_id_seq');

CREATE SEQUENCE user_results_id_seq;
ALTER TABLE user_results ALTER COLUMN id SET DEFAULT nextval('user_results_id_seq');

ALTER TABLE questions
ALTER COLUMN question_id SET DATA TYPE INTEGER,
ALTER COLUMN question_id SET DEFAULT nextval('questions_id_seq');